### PR TITLE
coffee support

### PR DESCRIPTION
**Pull request by dvv**
Please, consider applying

### CODE REVIEW

**Comment by tj** [comment]
closing for now

**Comment by dvv** [comment]
sure thing

**Comment by kainosnoema** [comment]
I know you're not a CoffeeScript fan, but some of us really are and we've got apps that we'd like to run on Cluster. Any chance you'd reconsider? I'd rather not fork...

By the way, this is what I'm getting when I try to start the example "Hello World" app from cluster-live using coffee:

```
Error: ENOTTY, Inappropriate ioctl for device
    at new Interface (readline.js:80:9)
    at Object.createInterface (readline.js:38:10)
    at Object.<anonymous> (/Users/kainosnoema/.nvm/v0.4.6/lib/node/.npm/coffee-script/1.0.1/package/lib/repl.js:39:21)
    at Object.<anonymous> (/Users/kainosnoema/.nvm/v0.4.6/lib/node/.npm/coffee-script/1.0.1/package/lib/repl.js:47:4)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at Object.run (/Users/kainosnoema/.nvm/v0.4.6/lib/node/.npm/coffee-script/1.0.1/package/lib/command.js:47:14)
```

**Comment by tj** [comment]
just compile your CS to js first

**Comment by kainosnoema** [comment]
Ya we always do that for production... was hoping for easier testing but no worries.

**Comment by tj** [comment]
haha exactly :p compiling your dynamic language becomes slightly less fun

**Comment by TrevorBurnham** [comment]
@dvv I've raised a pull request for CoffeeScript to set `process.execPath` to `coffee`, which would remove the need for Cluster to do any special-casing, n'est pas? https://github.com/jashkenas/coffee-script/pull/1307

**Pull request closed without merging**
