### PR TITLE
Set process title to indicate whether it's a master or a worker

### PR DESCRIPTION
**Pull request by wereHamster**
I'd like to know which process is the master and which are the workers. This tiny commits sets process.title in the Master constructor to change the process name as it appears in ps.

### CODE REVIEW

**Comment by tj** [comment]
Cool ill merge on monday, although you can tell by the pgid

**Comment by tj** [comment]
pretty sure process.title doesn't even work on osx :(

**Comment by tj** [comment]
nor top / htop :(

**Comment by wereHamster** [comment]
On 3/16/11 12:23 AM, visionmedia wrote:

> nor top / htop :(

Feel free to ignore the pull request then..

**Comment by tj** [comment]
we should at support for it as `.set('title', 'whatever')` and maybe append ' - worker N' etc, defaulting to "cluster" I suppose. sucks that it doesnt work on osx

**Comment by 3rd-Eden** [comment]
I never had any issues with using process.title on Mac OSX ( using Mac OSX 10.6 & node 0.4.x )

**Comment by tj** [comment]
hm, I dont see it in top, htop, or ps

**Comment by 3rd-Eden** [comment]
It does show up in the "Activity Monitor"

**Comment by tj** [comment]
oh, pff, who uses that

**Comment by 3rd-Eden** [comment]
Ok you have a point there but also Instruments.app shows the `process.title`. Which is useful for debugging your node apps, searching for memory leaks, adding dtrace probes etc.

**Comment by tj** [comment]
im not against the title setting at all, I was just hoping to try it out first and couldnt get it to work haha, I'll add it

**Comment by tj** [comment]
Added `title` and `worker title` settings. Closed by 739bd6df4ba09f420a0a991402c97500fdb50678

**Comment by tj** [comment]
Activity Monitor did work, sucks that htop and friends dont

**Comment by 3rd-Eden** [comment]
Yeh that is annoying, but at least the process will be easier to identify now, instead of guessing which node process is what.

**Comment by tj** [comment]
yeah totally, its pretty easy for me usually since you can see N children under the one master node, but if you have several clusters running that would get a bit messy

**Pull request closed without merging**
